syntax = "proto3";

package raftpb;

service RaftService {
  rpc AppendEntries(AppendEntriesRequest) returns (AppendEntriesReply);
  rpc RequestVote(RequestVoteRequest) returns (RequestVoteReply);
}

message Entry {
  uint64 index = 1;
  uint64 term = 2;
  bytes command = 3;
}

message AppendEntriesRequest {
  uint64 term = 1;
  uint64 leader_id = 2;
  uint64 prev_log_index = 3;
  uint64 prev_log_term = 4;
  repeated Entry entries = 5;
  uint64 leader_commit = 6;
}

message AppendEntriesReply {
  uint64 term = 1;
  bool success = 2;
}

message RequestVoteRequest {
  uint64 term = 1;
  uint64 candidate_id = 2;
  uint64 last_log_index = 3;
  uint64 last_log_term = 4;
}

message RequestVoteReply {
  uint64 term = 1;
  bool vote_granted = 2;
}
